### PR TITLE
Update RSBypass.m

### PR DESCRIPTION
**Pull request by 0x0L**
Remastered patch

### CODE REVIEW

**Comment by fabianosan** [comment]
Thanks...

**Comment by nsanta** [comment]
Any chance to do a release of this patch soon? Thanks.

**Comment by L0FKA** [comment]
@nsanta here link for pc and mac, so you don't need to play with travis now :3
(http://customsforge.com/topic/33138-rocksmith-remastered-cdlc-fix/)

also, @ray can we put official release asap too?

**Comment by nsanta** [comment]
Thank you!

**Comment by ray** [comment]
I've published a release but I don't have the game installed on my OSX VM so have no way to test it

**Comment by 0x0L** [comment]
@ray works fine on my sierra machine, thanks

**Pull request merged**
